[package]
name = "noop-bus-mutex"
version = "0.1.0"
authors = ["Florian Jung <flo@windfisch.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared-bus = ">=0.1.4"
